<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <title>e-Prescription</title>
    <style>
        p{
            margin-bottom: 0;
            padding: 0;
            font-size: 12px;
        }
        hr{
            height: .5%;
            color: black;
        }
        .column {
        float: left;
        }
        .left{
            width: 70%;
        }
        .right{
            width: 30%;
        }
        .row:after {
        content: "";
        display: table;
        clear: both;
        }

        table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        }

        td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
        font-size: 10px;
        }
        .bottomleft {
        position: absolute;
        bottom: 130px;
        left: 55px;
        font-size: 13px;
        }
        span{
            display:inline-block;
            border-top:1px solid black;
            padding-top:4px;
        }
        @page {
	footer: page-footer;
}
    </style>
</head>
<body>
    <div style="text-align: center">
        <h3>{{$data['clinician']['clinic_name']}}</h3>
        <p>e-Prescription</p>
    </div>

    <div style="margin-top:20px">
        <p style="text-transform: uppercase"><strong>Dr. {{$data['clinician']['first_name']}} {{$data['clinician']['middle_name'][0]}}. {{$data['clinician']['last_name']}} {{$data['clinician']['suffix']}}</strong></p>
    </div>

    <div style="margin-top:20px">
        <p>License No: {{$data['clinician']['license_number']}}</p>
        <p>PTR No: {{$data['clinician']['ptr_number']}}</p>
        <p>Address: {{$data['clinician']['address']}}</p>
        <p>Schedule (Monday to Saturday): 4:00 PM - 6:00 PM</p>
    </div>
    <br>
    <hr>
    <div class="row">
        <div class="column left" >
            <p><strong>Name: </strong>{{$data['patient']['first_name']}} {{$data['patient']['middle_name'][0]}}. {{$data['patient']['last_name']}} {{$data['patient']['suffix']}}</p>
        </div>
        <div class="column right">
            <p><strong>Birth Date: </strong>{{$data['patient']['birthdate']}}</p>
        </div>
    </div>
    <div class="row">
        <div class="column left">
            <p><strong>Address: </strong>{{$data['patient']['address']}}</p>
        </div>
        <div class="column right">
            <p><strong>Sex: </strong>{{$data['patient']['sex']}}</p>
        </div>
    </div>
    <br>
    <hr>
    <div>
        <h1>Rx</h1>
    </div>
    <table>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Medicine</th>
            <th scope="col">Brand</th>
            <th scope="col">Form</th>
            <th scope="col">Frequency</th>
            <th scope="col">Duration</th>
            <th scope="col">Instruction</th>
        </tr>
        <tr>
          <@php($i=1)
          @foreach ($prescription as $prescription)
              <tr>
                  <th scope="row">{{$i++}}</th>
                  <td>{{$prescription['medicine']}}</td>
                  <td>{{$prescription['brand']}}</td>
                  <td>{{$prescription['form']}}</td>
                  <td>{{$prescription['frequency']}} time/s a day</td>
                  <td>{{$prescription['duration']}} day/s</td>
                  <td>{{$prescription['instruction']}}</td>
                  
              </tr>
          @endforeach
        </tr>
        
    </table>
    
    <p class="bottomleft"><span>Doctor's Signature</span></p>
    
    <htmlpagefooter name="page-footer">
        <p style="text-align: justify"><i>This prescription is auto-generated by the system. Any information changed manually or electronically, prescriber or creator will not be liable. Generated on {{$data['datetime']}}.</i></p>
    </htmlpagefooter>
    



</body>
</html>


